### ISSUE TITLE
Backup and restore - any expected issues?

### ISSUE THREAD

**Issue by RickCogley** [neatnik/steganographr#6]
Just a quick question. If I store the encoded strings in a database, can you foresee any problems with a typical Db backup and restore process, vis-a-vis the hidden characters you are using? For example, dumping a csv or sql file and reloading it? 

Indeed & more basically, can you foresee any problems storing the encoded strings in a db text field?

**Comment by RickCogley** [comment]
I did some testing. Exporting data with encoded strings from a MS SQL db to a csv and an Excel, the encoding is preserved on export, and on re-import after clearing the relevant fields in the db. 

Looking at the exported csv in a text editor, one can't see the hidden chars, but they are there if you copy the string, then use the steganographer API to decode. Same test works with Excel, except, there's a visual artifact in Excel that, when you double click on the cell containing the encoded data, Excel visually splits the string, so that it looks like something's somehow off with the string in that particular cell. See the screenshot below.  

So I assume the answer to the question is "it depends" on whether the db has its code page set up correctly, and any script you're using to export or import can support "all unicode" or not. 

<img width="617" alt="image" src="https://user-images.githubusercontent.com/512328/95929284-97871a00-0dfe-11eb-91d1-daf8598a5f86.png">

**Comment by newbold** [comment]
Yeah, you pretty much hit the nail on the head here. "It depends" is going to be the answer to a ton of stuff when it comes to these more rarely used Unicode characters. What you've noticed in Excel can be seen elsewhere, including right here in GitHub where you can have a string like "There's a messa﻿‌​​‌​​​⁠‌‌​‌​​‌⁠‌‌​​‌​​⁠‌‌​​‌​​⁠‌‌​​‌​‌⁠‌‌​‌‌‌​⁠‌​​​​‌﻿ge hidden here." and nobody could tell there's anything hiding in there at a glance (though the red-lined squiggly spell check indicator just activated on the word "message", which contains the hidden chars), but if you wrap the same string in code Markdown syntax the hidden stuff is exposed, like this: `"There's a messa﻿‌​​‌​​​⁠‌‌​‌​​‌⁠‌‌​​‌​​⁠‌‌​​‌​​⁠‌‌​​‌​‌⁠‌‌​‌‌‌​⁠‌​​​​‌﻿ge hidden here."` Then you can run into the opposite problem, where in some contexts the invisible characters are stripped out of things entirely (within systems that don't know how to handle them, or that have databases that aren't set up to properly store those characters). This is exactly the kind of stuff that should be documented in the wiki that I'm going to set up soon (at your suggestion).

But back to the original question about databases: as you found, everything will be fine as long as the database is configured to tolerate the kind of encoding that's used within the hidden characters. I don't have much experience with MS SQL, but I know in MySQL it's just a matter of defining a collation that supports multibyte encoding. Since you work with Japanese content, I'm guessing your database is already good to go on multibyte stuff. I think most databases handle multibyte stuff just fine by default (though I've found that trying to store emoji in MySQL can be kind of tricky since some emoji characters are, like, _multi_-multi-byte and need a more specific collation... but that's another story entirely.)

**Comment by RickCogley** [comment]
Thanks for the detailed answer, confirming my suspicions (there's always _something_ lol). For my use case, everything seems to be working as expected including backup and restore, and in Japanese to boot. There's a lot of moving parts, but it's really useful tech. :-)

**Comment by RickCogley** [comment]
FYI, an update. Besides my self-tests, I asked support at the provider whose platform we use for building business apps if they had any comment on using the characters: 

- WORD JOINER (U+2060)
- ZERO WIDTH SPACE (U+200B)
- ZERO WIDTH NON-JOINER (U+200C)
- ZERO WIDTH NON-BREAKING SPACE (U+FEFF)

... with regard to general UI ops, or backup and restore. 

They said: 

> We indeed do certain "normalization". All forms of line feed, such as U+000D, U+000A, U+2028, U+2029 are all translated to U+000D U+000A pairs.
> 
> Spaces, such as U+00A0, U+1680, U+2000 to U+200A, U+202F, U+205F, U+3000 are translated to ASCII white space U+0020. 
> 
> Control characters in range U+0000 to U+001F, U+007F, and U+0080 to U+009F except for line breaks and tab (U+0009) are removed.
> 
> The rest is stored in the database intact.
> 
> Neither U+2060, nor U+200B and U+200C are the subject of normalization.

I followed up about U+FEFF, and they said: 

> We do not normalize it, but in fact U+FEFF has a limited use: It should appear in the beginning of text files to indicate the file contains UTF-16 characters, and just that.

I know you added the U+FEFF bullet in a recent commit. Given the above comment, do you think it will be a problem?

**Comment by newbold** [comment]
It shouldn't be a problem. The character is often referred to as the "[byte order mark](https://en.wikipedia.org/wiki/Byte_order_mark)" and there's a convention of using it in the way that your provider stated, but it's still a perfectly valid character and can be used anywhere (it just isn't really _useful_ anywhere, since it's invisible). But in Steganographr's context, it's very useful. 😄 

The tricky thing here is that there’s a very limited number of "invisible" [whitespace characters](https://en.wikipedia.org/wiki/Whitespace_character) that Steganographr could use. There are only five standard unicode characters that do not produce any visible output (and that aren't control characters or other characters that can't really be included in text), and until adding U+FEFF I was using three of them. After U+FEFF, there's only one left, but fortunately I don't think there are any other scenarios in which the encoding process would need to rely on any additional invisible characters. (Though in all fairness, I was equally confident prior to your discovery of what I'm calling the "accidental binary conflict".)

**Comment by RickCogley** [comment]
I will try to stay away from any more edges, lol 😆

**Comment by newbold** [comment]
No, by all means keep them coming! This is exactly the way that projects like these become stronger and more resilient.

**Comment by RickCogley** [comment]
No problem; I just can’t resist a good edge. :-)
